---
title: "Off-target splice actionable by drugs"
output: html_notebook
---

```{r}
library(tidyverse)
library(data.table)
```
set wd 
```{r setup, include=FALSE, echo=FALSE}
require("knitr")
opts_knit$set(root.dir = "/Users/castilln/Desktop/thesis/localdata")
```

Load offtarget splice variations
```{r}
off_target = readRDS("spliceai/Dependencies_offTarget_spliceAI.rds")

tsh8 = readRDS("../github/results/spliceAI/ths8.rds")
tsh5 = readRDS("../github/results/spliceAI/ths5.rds")

head(tsh5)
```
Select only variables of interest 
```{r}
df8 = 
  tsh8 %>% 
  select(c("DepMap_ID", "SYMBOL", "primary_disease"))


df5 = 
  tsh5 %>% 
  select(c("DepMap_ID", "SYMBOL", "primary_disease"))
```

Load drug info 
```{r}
drug_rep = read_tsv("depmap/repurposing_drugs_20200324.txt")

##AND CCLE MUTATIONS INFO 
ccle = read_csv("depmap/CCLE_info")
```
Add cancer information to off_targets
```{r}
ccle_small = 
  ccle %>% 
  select(c("DepMap_ID", "primary_disease")) %>% 
  unique()

off_target_ann = 
  off_target %>% 
  left_join(ccle_small, by = "DepMap_ID")

head(off_target_ann)
```


Keep only oncology drugs
```{r}
drug_onc = 
  drug_rep %>% 
  filter(disease_area == "oncology") %>% 
  drop_na()
```

Parse multiple target Symbols to different columns
```{r}
library(splitstackshape)
pars_drug_onc = cSplit(as.data.table(drug_onc), "target", "|")

pars_drug_onc = 
  pars_drug_onc %>% 
  select(-c("clinical_phase", "disease_area"))

head(pars_drug_onc)

#PIVOT LONGER
target_list = 
  pars_drug_onc %>% 
  pivot_longer(cols = -c("pert_iname", "moa", "indication"), names_to = "t", values_to = "SYMBOL") %>% 
  select(-t) %>% 
  drop_na()

head(target_list)
```

```{r}
res = 
  left_join(off_target_ann, target_list, by = "SYMBOL") %>% 
  drop_na(pert_iname)
```

Repeat analysis for spliceAI predictions with probability > 0.8
```{r}
res8 = 
  left_join(df8, target_list, by = "SYMBOL") %>% 
  drop_na(pert_iname)

head(res8)
```

```{r}
res5 = 
  left_join(df5, target_list, by = "SYMBOL") %>% 
  drop_na(pert_iname)

head(res5)
```


